# Generated by Django 5.1.3 on 2024-11-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mandatory_non_mandatory_user_name',
            new_name='parent_name',
        ),
    ]
