# Generated by Django 5.1.3 on 2024-11-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_mandatory_non_mandatory_user_name_user_parent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='carers_parent_phone_number',
            new_name='parent_phone_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='carers_parent_surname',
            new_name='parent_surname',
        ),
    ]
