# Generated by Django 5.1.3 on 2024-11-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_carers_parent_phone_number_user_parent_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='term_and_condition_gdpr',
            field=models.BooleanField(default=False),
        ),
    ]
