# Generated by Django 5.0.6 on 2024-11-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_photo_consent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserData',
        ),
    ]
