# Generated by Django 5.0.6 on 2024-11-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_user_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackOfficeStaff',
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
