# Generated by Django 5.0.6 on 2024-11-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_backofficestaff_userdata_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
